#!/bin/bash
#
# File:    /etc/init.d/amixer-webui
# Date:    22. 1. 2016
# Author:  Jiri Skorpil <jiri.sko@gmail.com>
# Desc.:   System V init script for start/stop ALSA Mixer WebUI webserver
#

### BEGIN INIT INFO
# Provides:          ALSA Mixer WebUI webserver
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: amixer-webui
# Description:       ALSA Mixer WebUI webserver
### END INIT INFO

user= # user which will run the webserver (if not set will be used user who ran this script)
path=/usr/share/amixer-webui

startCommand="$path/alsamixer_webui.py"

pid="`ps ax | grep alsamixer_webui | grep -v grep | awk '{print $1}'`"

case "$1" in
  start)
    if [ "$pid" != "" ]
    then
      echo "alsamixer-webui already running"
    else
      cd $path
      if [ -z "$user" ]
      then
        $startCommand >/dev/null 2>&1 &
      else
        su $user - -c "$startCommand >/dev/null 2>&1 &"
      fi
      echo "alsamixer-webui started"
    fi
    ;;
  stop)
    if [ "$pid" != "" ]
    then
      author="`ps -f -p $pid | tail -1 | awk '{print $1}'`"
      if [ "$user" == "$author" ] || ([ -z "$user" ] && [ "$author" == "`whoami`" ])
      then
        kill -9 $pid > /dev/null 2>&1
      elif [ "$author" == "root" ]
      then
        sudo kill -9 $pid > /dev/null 2>&1
      else
        su $user - -c "kill -9 $pid > /dev/null 2>&1"
      fi
      echo "alsamixer-webui stopped"
    else
      echo "alsamixer-webui is not running"
    fi
    ;;
  status)
    if [ "$pid" != "" ]
    then
      echo "alsamixer-webui is running"
    else
      echo "alsamixer-webui is not running"
    fi
    ;;
  restart)
    /etc/init.d/amixer-webui stop
    /etc/init.d/amixer-webui start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
