#!/bin/sh /etc/rc.common
#
# File:    /etc/init.d/amixer-webui
# Date:    11. 7. 2016
# Author:  Jiri Skorpil <jiri.sko@gmail.com>
# Desc.:   procd init script for start/stop ALSA Mixer WebUI webserver on OpenWrt
#

EXTRA_COMMANDS="status"

START=99
STOP=0

path=/usr/share/amixer-webui

alsa_path=/var/lib/alsa
asound=asound.state

pid="`ps w | grep alsamixer_webui | grep -v grep | awk '{print $1}'`"

start() {
    if [ "$pid" != "" ]
    then
      echo "amixer-webui already running"
    else
      cd $path
      $path/alsamixer_webui.py >/dev/null 2>&1 &
      if [ ! -f "$alsa_path/$asound" ]; then
        if [ ! -d "$alsa_path" ]; then
            mkdir $alsa_path
        fi
        if [ -f "$path/$asound" ]; then
          cp $path/$asound $alsa_path/$asound
          alsactl restore
        else
          alsactl init
        fi
      fi
      echo "amixer-webui started"
    fi
}
stop() {
    if [ "$pid" != "" ]
    then
      kill -9 $pid > /dev/null 2>&1
      if [ -f "$path/$asound" ]; then
        cp $alsa_path/$asound $path/$asound
      fi
      echo "amixer-webui stopped"
    else
      echo "amixer-webui is not running"
    fi
}
status() {
    if [ "$pid" != "" ]
    then
      echo "amixer-webui is running"
    else
      echo "amixer-webui is not running"
    fi
}
